/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface _yamanote_db_stateRow {
  'schemaVersion': number|bigint;
}
export interface backupRow {
  'id'?: number|bigint | null;
  'bookmarkId': number|bigint;
  'content': string;
  'createdTime': number;
}
export interface bookmarkRow {
  'id'?: number|bigint | null;
  'userId': number|bigint;
  'url': string;
  'title': string;
  'createdTime': number;
  'modifiedTime': number;
  'render': string;
  'renderedTime': number;
}
export interface commentRow {
  'id'?: number|bigint | null;
  'bookmarkId': number|bigint;
  'content': string;
  'createdTime': number;
  'modifiedTime': number;
  'render': string;
  'renderedTime': number;
}
export interface mediaRow {
  'id'?: number|bigint | null;
  'path': string;
  'mime': string;
  'content': Buffer|string|Uint8Array;
  'createdTime': number;
  'numBytes': number|bigint;
}
export interface userRow {
  'id'?: number|bigint | null;
  'name': string;
  'hashed': string;
  'salt': string;
  'iterations': number|bigint;
  'keylen': number|bigint;
  'digest': string;
}
