/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface _yamanote_db_stateRow {
  'schemaVersion': number;
}
export interface backupRow {
  'id'?: number | null;
  'bookmarkId': number;
  'content': string;
  'createdTime': number;
}
export interface bookmarkRow {
  'id'?: number | null;
  'userId': number;
  'url': string;
  'title': string;
  'createdTime': number;
  'modifiedTime': number;
  'render': string;
  'renderedTime': number;
}
export interface commentRow {
  'id'?: number | null;
  'bookmarkId': number;
  'content': string;
  'createdTime': number;
  'modifiedTime': number;
  'render': string;
  'renderedTime': number;
}
export interface mediaRow {
  'id'?: number | null;
  'base64': string;
  'createdTime': number;
  'checksumValue': string;
  'checksumAlgo': string;
}
export interface userRow {
  'id'?: number | null;
  'name': string;
  'hashed': string;
  'salt': string;
  'iterations': number;
  'keylen': number;
  'digest': string;
}
