/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface _yamanote_db_stateRow {
  'schemaVersion': number|bigint;
}
export interface backupRow {
  'id'?: number|bigint | null;
  'bookmarkId': number|bigint;
  'content': string;
  'original': string;
  'createdTime': number;
}
export interface blobRow {
  'id'?: number|bigint | null;
  'content': Buffer|string|Uint8Array;
  'mime': string;
  'createdTime': number;
  'numBytes': number|bigint;
  'sha256': string;
}
export interface bookmarkRow {
  'id'?: number|bigint | null;
  'userId': number|bigint;
  'url': string;
  'title': string;
  'createdTime': number;
  'modifiedTime': number;
  'numComments': number|bigint;
  'render': string;
  'renderedTime': number;
}
export interface commentRow {
  'id'?: number|bigint | null;
  'bookmarkId': number|bigint;
  'siblingIdx': number|bigint;
  'content': string;
  'createdTime': number;
  'modifiedTime': number;
  'innerRender': string;
  'fullRender': string;
  'renderedTime': number;
}
export interface mediaRow {
  'id'?: number|bigint | null;
  'path': string;
  'bookmarkId': number|bigint;
  'sha256': string;
  'createdTime': number;
}
export interface tokenRow {
  'token': string;
  'description': string;
  'userId': number|bigint;
}
export interface userRow {
  'id'?: number|bigint | null;
  'displayName': string;
  'githubId': number|bigint;
}
